<!DOCTYPE html>
<html lang="en">
    <head>
        <title>HCJ3D - HTML, CSS, and JavaScript in 3D</title>
        <meta charset="utf-8">
        <meta name="description" content="HTML, CSS, and JavaScript in 3D">
        <meta name="property" content="HTML, CSS, and JavaScript in 3D">
        <link rel="stylesheet" type="text/css" href="/css/style.css?v=2017102701">
    </head>
    <body>
        <?= $this->content ?>
    </body>
</html>
