<!DOCTYPE html>
<html lang="en">
    <head>
        <title>HCJ3D - HTML, CSS, and JavaScript in 3D</title>
        <meta charset="utf-8">
        <meta name="description" content="HTML, CSS, and JavaScript in 3D">
        <meta name="property" content="HTML, CSS, and JavaScript in 3D">
        <link rel="stylesheet" type="text/css" href="/css/style.css?v=2017102701">
    </head>
    <body>
        <header>
            <h1>HCJ3D</h1>
        </header>

        <main>
            <hcj3d-world>
                <hcj3d-view>
                    <hcj3d-ground>
                    </hcj3d-ground>
                </hcj3d-view>
            </hcj3d-world>
        </main>

        <footer>
            <div>Use WSAD keys to move, arrow keys to look</div>
        </footer>
    </body>
</html>
