<!DOCTYPE html>
<html lang="en">
    <head>
        <title>HCJ3D - HTML, CSS, and JavaScript in 3D</title>
        <meta charset="utf-8">
        <meta name="description" content="HTML, CSS, and JavaScript in 3D">
        <meta name="property" content="HTML, CSS, and JavaScript in 3D">
        <meta property="fb:app_id" content="358318594591390">
        <meta property="fb:admins" content="4803002">
        <link rel="stylesheet" type="text/css" href="/css/font-awesome-4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css?v=<?= md5(microtime(true)); ?>">
        <link rel="stylesheet" type="text/css" href="/css/hcj3d.css?v=<?= md5(microtime(true)); ?>">

        <script src="/css/fontawesome-free-5.0.6/svg-with-js/js/fontawesome-all.js"></script>

        <script src="/js/jquery-3.3.1.min.js"></script>

        <script src="/js/Model/Entity/Cube.js"></script>
        <script src="/js/Model/Entity/Mannequin.js"></script>
        <script src="/js/Model/Entity/Point.js"></script>
        <script src="/js/Model/Service/Ajax.js"></script>
        <script src="/js/Model/Service/Array.js"></script>
        <script src="/js/Model/Service/Cube.js"></script>
        <script src="/js/Model/Service/Cube/Draw.js"></script>
        <script src="/js/Model/Service/Cubes.js"></script>
        <script src="/js/Model/Service/Mannequin/Draw.js"></script>
        <script src="/js/Model/Service/Mannequin/Move.js"></script>
        <script src="/js/Model/Service/Points.js"></script>

        <script src="/js/main.js?v=<?= md5(microtime(true)); ?>"></script>

        <?php if (!empty($_SERVER['HTTP_HOST']) && ($_SERVER['HTTP_HOST'] == 'www.hcj3d.com')): ?>
            <!-- Global site tag (gtag.js) - Google Analytics -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-42535259-27"></script>
            <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'UA-42535259-27');
            </script>
        <?php endif ?>
    </head>
    <body>
        <header>
            <div class="left">
                <h1>HCJ3D</h1>
                <span>HTML, CSS, and<br>JavaScript in 3D</span>
            </div>
            <div>
                Refresh browser to spawn in random location.<br>
                Then, use arrow keys to look and WASD keys to move.
            </div>
        </header>

        <main>
            <hcj3d-world>
                <hcj3d-view>
                    <hcj3d-perspective>
                        <hcj3d-ground
                            class="grass"
                            style="transform: translateX(0px) translateY(0px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="rocks"
                            style="transform: translateX(0px) translateY(1000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="half-rombes"
                            style="transform: translateX(0px) translateY(2000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="carbon-fibre"
                            style="transform: translateX(0px) translateY(3000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            style="background-color: rgb(213, 120, 93); transform: translateX(0px) translateY(4000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="dirt"
                            style="transform: translateX(1000px) translateY(0px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="arrows"
                            style="transform: translateX(1000px) translateY(1000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="marrakesh"
                            style="transform: translateX(1000px) translateY(2000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="waves"
                            style="transform: translateX(1000px) translateY(3000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            style="background-color: rgb(143, 10, 201); transform: translateX(1000px) translateY(4000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="checkerboard"
                            style="transform: translateX(2000px) translateY(0px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="shippo"
                            style="transform: translateX(2000px) translateY(1000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="steps"
                            style="transform: translateX(2000px) translateY(2000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="diagonal-stripes"
                            style="transform: translateX(2000px) translateY(3000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            style="background-color: rgb(123, 45, 49); transform: translateX(2000px) translateY(4000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="bricks"
                            style="transform: translateX(3000px) translateY(0px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="tablecloth"
                            style="transform: translateX(3000px) translateY(1000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="weave"
                            style="transform: translateX(3000px) translateY(2000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="zig-zag"
                            style="transform: translateX(3000px) translateY(3000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            style="background-color: rgb(204, 98, 1); transform: translateX(3000px) translateY(4000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="bricks"
                            style="transform: translateX(4000px) translateY(0px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="tablecloth"
                            style="transform: translateX(4000px) translateY(1000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="weave"
                            style="transform: translateX(4000px) translateY(2000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            class="zig-zag"
                            style="transform: translateX(4000px) translateY(3000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-ground
                            style="background-color: rgb(204, 98, 1); transform: translateX(4000px) translateY(4000px) translateZ(0px);"
                        ></hcj3d-ground>
                        <hcj3d-mannequin id="me">
                            <hcj3d-mannequin-leg class="left">
                                <hcj3d-mannequin-leg-bottom></hcj3d-mannequin-leg-bottom>
                                <hcj3d-mannequin-leg-top></hcj3d-mannequin-leg-top>
                                <hcj3d-mannequin-leg-left></hcj3d-mannequin-leg-left>
                                <hcj3d-mannequin-leg-right></hcj3d-mannequin-leg-right>
                                <hcj3d-mannequin-leg-front></hcj3d-mannequin-leg-front>
                                <hcj3d-mannequin-leg-back></hcj3d-mannequin-leg-back>
                            </hcj3d-mannequin-leg>
                            <hcj3d-mannequin-leg class="right">
                                <hcj3d-mannequin-leg-bottom></hcj3d-mannequin-leg-bottom>
                                <hcj3d-mannequin-leg-top></hcj3d-mannequin-leg-top>
                                <hcj3d-mannequin-leg-left></hcj3d-mannequin-leg-left>
                                <hcj3d-mannequin-leg-right></hcj3d-mannequin-leg-right>
                                <hcj3d-mannequin-leg-front></hcj3d-mannequin-leg-front>
                                <hcj3d-mannequin-leg-back></hcj3d-mannequin-leg-back>
                            </hcj3d-mannequin-leg>
                            <hcj3d-mannequin-body>
                                <hcj3d-mannequin-body-bottom></hcj3d-mannequin-body-bottom>
                                <hcj3d-mannequin-body-top></hcj3d-mannequin-body-top>
                                <hcj3d-mannequin-body-left></hcj3d-mannequin-body-left>
                                <hcj3d-mannequin-body-right></hcj3d-mannequin-body-right>
                                <hcj3d-mannequin-body-front></hcj3d-mannequin-body-front>
                                <hcj3d-mannequin-body-back>
                                    <div class="name"></div>
                                </hcj3d-mannequin-body-back>
                            </hcj3d-mannequin-body>
                            <hcj3d-mannequin-head>
                                <hcj3d-mannequin-head-bottom></hcj3d-mannequin-head-bottom>
                                <hcj3d-mannequin-head-top></hcj3d-mannequin-head-top>
                                <hcj3d-mannequin-head-left></hcj3d-mannequin-head-left>
                                <hcj3d-mannequin-head-right></hcj3d-mannequin-head-right>
                                <hcj3d-mannequin-head-front></hcj3d-mannequin-head-front>
                                <hcj3d-mannequin-head-back></hcj3d-mannequin-head-back>
                            </hcj3d-mannequin-head>
                        </hcj3d-mannequin>
                    </hcj3d-perspective>
                </hcj3d-view>
            </hcj3d-world>
        </main>

        <footer>
            <div class="bottom-left">
                <ol>
                    <li id="w">W</li>
                    <li id="a">A</li>
                    <li id="s">S</li>
                    <li id="d">D</li>
                    <li id="left">left</li>
                    <li id="right">right</li>
                    <li id="up">up</li>
                    <li id="down">down</li>
                    <li id="space-bar">SPACE</li>
                </ol>
            </div>
            <div>
                <ol>
                    <li>
                        <a href="https://www.facebook.com/HCJ3D" target="_blank"><i class="fab fa-fw fa-facebook-f"></i></a>
                    </li>
                    <li>
                        <a href="https://github.com/HCJ3D" target="_blank"><i class="fab fa-fw fa-github"></i></a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/hcj3d/" target="_blank"><i class="fab fa-fw fa-instagram"></i></a>
                    </li>
                    <li>
                        <a href="https://twitter.com/HCJ3D" target="_blank"><i class="fab fa-fw fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/channel/UCuRs1PD9ouT5Y9SfUlHJSXQ" target="_blank"><i class="fab fa-fw fa-youtube"></i></a>
                    </li>
                </ol>
            </div>
        </footer>

        <div id="body" class="dialog" style="display: none;">
            <form>
                Name <input type="text" name="name">
                <input type="submit" value="Submit">
            </form>
        </div>
    </body>
</html>
