<!DOCTYPE html>
<html lang="en">
    <head>
        <title>HCJ3D - HTML, CSS, and JavaScript in 3D</title>
        <meta charset="utf-8">
        <meta name="description" content="HTML, CSS, and JavaScript in 3D">
        <meta name="property" content="HTML, CSS, and JavaScript in 3D">
        <meta property="fb:app_id" content="358318594591390">
        <meta property="fb:admins" content="4803002">
        <link rel="stylesheet" type="text/css" href="/css/font-awesome-4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css?v=2018031202">
        <link rel="stylesheet" type="text/css" href="/css/hcj3d.css?v=2018031202">

        <script src="/css/fontawesome-free-5.0.6/svg-with-js/js/fontawesome-all.js"></script>

        <script src="/js/jquery-3.3.1.min.js"></script>

        <script src="/js/Model/Entity/Cube.js"></script>
        <script src="/js/Model/Entity/Point.js"></script>
        <script src="/js/Model/Service/Ajax.js"></script>
        <script src="/js/Model/Service/Array.js"></script>
        <script src="/js/Model/Service/Cube.js"></script>
        <script src="/js/Model/Service/Cubes.js"></script>
        <script src="/js/Model/Service/Points.js"></script>

        <script src="/js/main.js?v=2018031202"></script>

        <?php if (!empty($_SERVER['HTTP_HOST']) && ($_SERVER['HTTP_HOST'] == 'www.hcj3d.com')): ?>
            <!-- Global site tag (gtag.js) - Google Analytics -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-42535259-27"></script>
            <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'UA-42535259-27');
            </script>
        <?php endif ?>
    </head>
    <body>
        <header>
            <div class="left">
                <h1>HCJ3D</h1>
                <span>HTML, CSS, and<br>JavaScript in 3D</span>
            </div>
            <div>Optimized for Chrome</div>
        </header>

        <main>
            <hcj3d-world>
                <hcj3d-view>
                    <hcj3d-perspective>
                        <hcj3d-ground>
                            <hcj3d-mannequin>
                                <hcj3d-mannequin-leg class="left">
                                    <hcj3d-mannequin-leg-bottom></hcj3d-mannequin-leg-bottom>
                                    <hcj3d-mannequin-leg-top></hcj3d-mannequin-leg-top>
                                    <hcj3d-mannequin-leg-left></hcj3d-mannequin-leg-left>
                                    <hcj3d-mannequin-leg-right></hcj3d-mannequin-leg-right>
                                    <hcj3d-mannequin-leg-front></hcj3d-mannequin-leg-front>
                                    <hcj3d-mannequin-leg-back></hcj3d-mannequin-leg-back>
                                </hcj3d-mannequin-leg>
                                <hcj3d-mannequin-leg class="right">
                                    <hcj3d-mannequin-leg-bottom></hcj3d-mannequin-leg-bottom>
                                    <hcj3d-mannequin-leg-top></hcj3d-mannequin-leg-top>
                                    <hcj3d-mannequin-leg-left></hcj3d-mannequin-leg-left>
                                    <hcj3d-mannequin-leg-right></hcj3d-mannequin-leg-right>
                                    <hcj3d-mannequin-leg-front></hcj3d-mannequin-leg-front>
                                    <hcj3d-mannequin-leg-back></hcj3d-mannequin-leg-back>
                                </hcj3d-mannequin-leg>
                                <hcj3d-mannequin-body>
                                    <hcj3d-mannequin-body-bottom></hcj3d-mannequin-body-bottom>
                                    <hcj3d-mannequin-body-top></hcj3d-mannequin-body-top>
                                    <hcj3d-mannequin-body-left></hcj3d-mannequin-body-left>
                                    <hcj3d-mannequin-body-right></hcj3d-mannequin-body-right>
                                    <hcj3d-mannequin-body-front></hcj3d-mannequin-body-front>
                                    <hcj3d-mannequin-body-back></hcj3d-mannequin-body-back>
                                </hcj3d-mannequin-body>
                                <hcj3d-mannequin-head>
                                    <hcj3d-mannequin-head-bottom></hcj3d-mannequin-head-bottom>
                                    <hcj3d-mannequin-head-top></hcj3d-mannequin-head-top>
                                    <hcj3d-mannequin-head-left></hcj3d-mannequin-head-left>
                                    <hcj3d-mannequin-head-right></hcj3d-mannequin-head-right>
                                    <hcj3d-mannequin-head-front></hcj3d-mannequin-head-front>
                                    <hcj3d-mannequin-head-back></hcj3d-mannequin-head-back>
                                </hcj3d-mannequin-head>
                            </hcj3d-mannequin>
                            <hcj3d-cube style="transform: rotateX(0) rotateY(0) rotateZ(0) translateX(100px) translateY(200px) translateZ(0px);">
                                <hcj3d-cube-side side="bottom"></hcj3d-cube-side>
                                <hcj3d-cube-side side="top"></hcj3d-cube-side>
                                <hcj3d-cube-side side="left"></hcj3d-cube-side>
                                <hcj3d-cube-side side="right"></hcj3d-cube-side>
                                <hcj3d-cube-side side="front">
<iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FHCJ3D-368547880266829%2F&width=51&layout=button&action=like&size=small&show_faces=false&share=false&height=65&appId=358318594591390" width="51" height="20" style="display: block; margin: 0 auto; border:none; overflow:hidden; position: relative; top: 50%; transform: translateY(-50%);" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
                                </hcj3d-cube-side>
                                <hcj3d-cube-side side="back"></hcj3d-cube-side>
                            </hcj3d-cube>
                            <hcj3d-cube style="transform: rotateX(0) rotateY(0) rotateZ(0) translateX(700px) translateY(200px) translateZ(0px);">
                                <hcj3d-cube-side side="bottom"></hcj3d-cube-side>
                                <hcj3d-cube-side side="top"></hcj3d-cube-side>
                                <hcj3d-cube-side side="left"></hcj3d-cube-side>
                                <hcj3d-cube-side side="right"></hcj3d-cube-side>
                                <hcj3d-cube-side side="front"></hcj3d-cube-side>
                                <hcj3d-cube-side side="back">
<iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FHCJ3D-368547880266829%2F&width=51&layout=button&action=like&size=small&show_faces=false&share=false&height=65&appId=358318594591390" width="51" height="20" style="display: block; margin: 0 auto; border:none; overflow:hidden; position: relative; top: 50%; transform: translateY(-50%);" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
                                </hcj3d-cube-side>
                            </hcj3d-cube>
                        </hcj3d-ground>
                    </hcj3d-perspective>
                </hcj3d-view>
            </hcj3d-world>
        </main>

        <footer>
            <div class="bottom-left">
                <ol>
                    <li id="w">W</li>
                    <li id="a">A</li>
                    <li id="s">S</li>
                    <li id="d">D</li>
                    <li id="left">L</li>
                    <li id="right">R</li>
                </ol>
            </div>
            <div>
                <ol>
                    <li>
                        <a href="https://www.facebook.com/HCJ3D" target="_blank"><i class="fab fa-fw fa-facebook-f"></i></a>
                    </li>
                    <li>
                        <a href="https://github.com/HCJ3D" target="_blank"><i class="fab fa-fw fa-github"></i></a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/hcj3d/" target="_blank"><i class="fab fa-fw fa-instagram"></i></a>
                    </li>
                    <li>
                        <a href="https://twitter.com/HCJ3D" target="_blank"><i class="fab fa-fw fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/channel/UCuRs1PD9ouT5Y9SfUlHJSXQ" target="_blank"><i class="fab fa-fw fa-youtube"></i></a>
                    </li>
                </ol>
            </div>
        </footer>
    </body>
</html>
